/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package duanmau.GiaoDien;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author NguyenMinhHau_PS24488
 */
public class GiaoDienChinh extends javax.swing.JFrame {

    /**
     * Creates new form GiaoDienChinh
     */
    public GiaoDienChinh() {
        initComponents();
        setLayout();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tlbthanhcongcu = new javax.swing.JToolBar();
        btnchuyende = new javax.swing.JButton();
        btnnguoihoc = new javax.swing.JButton();
        btnkhoahoc = new javax.swing.JButton();
        btnhocvien = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnhuongdan = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btndangxuat = new javax.swing.JButton();
        btnthoat = new javax.swing.JButton();
        thanhtrangthai = new javax.swing.JPanel();
        lbthongtin = new javax.swing.JLabel();
        lbgio = new javax.swing.JLabel();
        manhinhchinh = new javax.swing.JPanel();
        mnbMenu = new javax.swing.JMenuBar();
        mnuHethong = new javax.swing.JMenu();
        mnidangnhap = new javax.swing.JMenuItem();
        mnidangxuat = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnidoimatkhau = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mnithoat = new javax.swing.JMenuItem();
        mnuQuanli = new javax.swing.JMenu();
        mnichuyende = new javax.swing.JMenuItem();
        mnikhoahoc = new javax.swing.JMenuItem();
        mninguoihoc = new javax.swing.JMenuItem();
        mnihocvien = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        mninhanvien = new javax.swing.JMenuItem();
        mnuThongke = new javax.swing.JMenu();
        mnibangdiem = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        mniluongnguoihoc = new javax.swing.JMenuItem();
        mnidiemchuyende = new javax.swing.JMenuItem();
        mnidoanhthu = new javax.swing.JMenuItem();
        mnuTrogiup = new javax.swing.JMenu();
        mnihuongdan = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        mnigioithieu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hệ thống quản lí đào tạo");
        setIconImage(new ImageIcon(getClass().getResource("/duanmau/image/icon/icon.png")).getImage());

        tlbthanhcongcu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tlbthanhcongcu.setRollover(true);
        tlbthanhcongcu.setEnabled(false);

        btnchuyende.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duanmau/image/icon/Documents-icon.png"))); // NOI18N
        btnchuyende.setText("Chuyên đề");
        btnchuyende.setFocusable(false);
        btnchuyende.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnchuyende.setMargin(new java.awt.Insets(2, 15, 2, 15));
        btnchuyende.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlbthanhcongcu.add(btnchuyende);

        btnnguoihoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duanmau/image/icon/people-icon.png"))); // NOI18N
        btnnguoihoc.setText("Người học");
        btnnguoihoc.setFocusable(false);
        btnnguoihoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnnguoihoc.setMargin(new java.awt.Insets(2, 15, 2, 15));
        btnnguoihoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlbthanhcongcu.add(btnnguoihoc);

        btnkhoahoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duanmau/image/icon/Courses-icon.png"))); // NOI18N
        btnkhoahoc.setText("Khóa học");
        btnkhoahoc.setFocusable(false);
        btnkhoahoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnkhoahoc.setMargin(new java.awt.Insets(2, 15, 2, 15));
        btnkhoahoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlbthanhcongcu.add(btnkhoahoc);

        btnhocvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duanmau/image/icon/Student-id-icon.png"))); // NOI18N
        btnhocvien.setText("Học viên");
        btnhocvien.setFocusable(false);
        btnhocvien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnhocvien.setMargin(new java.awt.Insets(2, 15, 2, 15));
        btnhocvien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlbthanhcongcu.add(btnhocvien);
        tlbthanhcongcu.add(jSeparator1);

        btnhuongdan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duanmau/image/icon/Lamp-icon.png"))); // NOI18N
        btnhuongdan.setText("Hướng dẫn");
        btnhuongdan.setFocusable(false);
        btnhuongdan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnhuongdan.setMargin(new java.awt.Insets(2, 15, 2, 15));
        btnhuongdan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlbthanhcongcu.add(btnhuongdan);
        tlbthanhcongcu.add(jSeparator2);

        btndangxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duanmau/image/icon/Apps-preferences-system-login-icon.png"))); // NOI18N
        btndangxuat.setText("Đăng xuất");
        btndangxuat.setFocusable(false);
        btndangxuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btndangxuat.setMargin(new java.awt.Insets(2, 15, 2, 15));
        btndangxuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlbthanhcongcu.add(btndangxuat);

        btnthoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duanmau/image/icon/Log-Out-icon.png"))); // NOI18N
        btnthoat.setText("Thoát");
        btnthoat.setFocusable(false);
        btnthoat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnthoat.setMargin(new java.awt.Insets(2, 15, 2, 15));
        btnthoat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlbthanhcongcu.add(btnthoat);

        thanhtrangthai.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));

        lbthongtin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbthongtin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duanmau/image/icon/information-icon.png"))); // NOI18N
        lbthongtin.setText("  Hệ quản lí đào tạo");

        lbgio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbgio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duanmau/image/icon/Time-And-Date-Alarm-Clock-icon.png"))); // NOI18N
        lbgio.setText(" 00:00:00 AM");

        javax.swing.GroupLayout thanhtrangthaiLayout = new javax.swing.GroupLayout(thanhtrangthai);
        thanhtrangthai.setLayout(thanhtrangthaiLayout);
        thanhtrangthaiLayout.setHorizontalGroup(
            thanhtrangthaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thanhtrangthaiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbthongtin, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbgio)
                .addGap(18, 18, 18))
        );
        thanhtrangthaiLayout.setVerticalGroup(
            thanhtrangthaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thanhtrangthaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lbthongtin, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addComponent(lbgio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        manhinhchinh.setBackground(new java.awt.Color(255, 255, 255));
        manhinhchinh.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout manhinhchinhLayout = new javax.swing.GroupLayout(manhinhchinh);
        manhinhchinh.setLayout(manhinhchinhLayout);
        manhinhchinhLayout.setHorizontalGroup(
            manhinhchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        manhinhchinhLayout.setVerticalGroup(
            manhinhchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
        );

        mnbMenu.setAlignmentX(1.0F);
        mnbMenu.setAlignmentY(1.0F);

        mnuHethong.setText("Hệ thống");
        mnuHethong.setMargin(new java.awt.Insets(3, 2, 3, 2));

        mnidangnhap.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnidangnhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duanmau/image/icon/Login-icon.png"))); // NOI18N
        mnidangnhap.setText("Đăng nhập");
        mnuHethong.add(mnidangnhap);

        mnidangxuat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnidangxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duanmau/image/icon/Apps-preferences-system-login-icon.png"))); // NOI18N
        mnidangxuat.setText("Đăng xuất");
        mnuHethong.add(mnidangxuat);
        mnuHethong.add(jSeparator3);

        mnidoimatkhau.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnidoimatkhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duanmau/image/icon/secrecy-icon.png"))); // NOI18N
        mnidoimatkhau.setText("Đổi mật khẩu");
        mnuHethong.add(mnidoimatkhau);
        mnuHethong.add(jSeparator4);

        mnithoat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        mnithoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duanmau/image/icon/Log-Out-icon.png"))); // NOI18N
        mnithoat.setText("Thoát");
        mnithoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnithoatActionPerformed(evt);
            }
        });
        mnuHethong.add(mnithoat);

        mnbMenu.add(mnuHethong);

        mnuQuanli.setText("Quản lí");
        mnuQuanli.setMargin(new java.awt.Insets(3, 2, 3, 2));

        mnichuyende.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnichuyende.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duanmau/image/icon/Documents-icon.png"))); // NOI18N
        mnichuyende.setText("Chuyên đề");
        mnuQuanli.add(mnichuyende);

        mnikhoahoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnikhoahoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duanmau/image/icon/Courses-icon.png"))); // NOI18N
        mnikhoahoc.setText("Khóa học");
        mnuQuanli.add(mnikhoahoc);

        mninguoihoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mninguoihoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duanmau/image/icon/people-icon.png"))); // NOI18N
        mninguoihoc.setText("Người học");
        mnuQuanli.add(mninguoihoc);

        mnihocvien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnihocvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duanmau/image/icon/Student-id-icon.png"))); // NOI18N
        mnihocvien.setText("Học viên");
        mnihocvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnihocvienActionPerformed(evt);
            }
        });
        mnuQuanli.add(mnihocvien);
        mnuQuanli.add(jSeparator5);

        mninhanvien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mninhanvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duanmau/image/icon/Slideshare-icon.png"))); // NOI18N
        mninhanvien.setText("Nhân viên");
        mninhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mninhanvienActionPerformed(evt);
            }
        });
        mnuQuanli.add(mninhanvien);

        mnbMenu.add(mnuQuanli);

        mnuThongke.setText("Thống kê");
        mnuThongke.setMargin(new java.awt.Insets(3, 2, 3, 2));

        mnibangdiem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mnibangdiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duanmau/image/icon/graph-icon.png"))); // NOI18N
        mnibangdiem.setText("Bảng điểm");
        mnuThongke.add(mnibangdiem);
        mnuThongke.add(jSeparator6);

        mniluongnguoihoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mniluongnguoihoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duanmau/image/icon/Count-tool-icon.png"))); // NOI18N
        mniluongnguoihoc.setText("Lượng người học");
        mniluongnguoihoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniluongnguoihocActionPerformed(evt);
            }
        });
        mnuThongke.add(mniluongnguoihoc);

        mnidiemchuyende.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mnidiemchuyende.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duanmau/image/icon/chart-icon.png"))); // NOI18N
        mnidiemchuyende.setText("Điểm chuyên đề");
        mnuThongke.add(mnidiemchuyende);

        mnidoanhthu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mnidoanhthu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duanmau/image/icon/cash-icon.png"))); // NOI18N
        mnidoanhthu.setText("Doanh thu");
        mnuThongke.add(mnidoanhthu);

        mnbMenu.add(mnuThongke);

        mnuTrogiup.setText("Trợ giúp");
        mnuTrogiup.setMargin(new java.awt.Insets(3, 2, 3, 2));

        mnihuongdan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        mnihuongdan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duanmau/image/icon/guide-icon.png"))); // NOI18N
        mnihuongdan.setText("Hướng dẫn sử dụng");
        mnuTrogiup.add(mnihuongdan);
        mnuTrogiup.add(jSeparator7);

        mnigioithieu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnigioithieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duanmau/image/icon/information-icon.png"))); // NOI18N
        mnigioithieu.setText("Giới thiệu sản phẩm");
        mnuTrogiup.add(mnigioithieu);

        mnbMenu.add(mnuTrogiup);
        mnuTrogiup.getAccessibleContext().setAccessibleDescription("");

        setJMenuBar(mnbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tlbthanhcongcu, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
            .addComponent(thanhtrangthai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(manhinhchinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tlbthanhcongcu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(manhinhchinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(thanhtrangthai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnithoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnithoatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnithoatActionPerformed

    private void mnihocvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnihocvienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnihocvienActionPerformed

    private void mninhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mninhanvienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mninhanvienActionPerformed

    private void mniluongnguoihocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniluongnguoihocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniluongnguoihocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoDienChinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnchuyende;
    private javax.swing.JButton btndangxuat;
    private javax.swing.JButton btnhocvien;
    private javax.swing.JButton btnhuongdan;
    private javax.swing.JButton btnkhoahoc;
    private javax.swing.JButton btnnguoihoc;
    private javax.swing.JButton btnthoat;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JLabel lbgio;
    private javax.swing.JLabel lbthongtin;
    private javax.swing.JPanel manhinhchinh;
    private javax.swing.JMenuBar mnbMenu;
    private javax.swing.JMenuItem mnibangdiem;
    private javax.swing.JMenuItem mnichuyende;
    private javax.swing.JMenuItem mnidangnhap;
    private javax.swing.JMenuItem mnidangxuat;
    private javax.swing.JMenuItem mnidiemchuyende;
    private javax.swing.JMenuItem mnidoanhthu;
    private javax.swing.JMenuItem mnidoimatkhau;
    private javax.swing.JMenuItem mnigioithieu;
    private javax.swing.JMenuItem mnihocvien;
    private javax.swing.JMenuItem mnihuongdan;
    private javax.swing.JMenuItem mnikhoahoc;
    private javax.swing.JMenuItem mniluongnguoihoc;
    private javax.swing.JMenuItem mninguoihoc;
    private javax.swing.JMenuItem mninhanvien;
    private javax.swing.JMenuItem mnithoat;
    private javax.swing.JMenu mnuHethong;
    private javax.swing.JMenu mnuQuanli;
    private javax.swing.JMenu mnuThongke;
    private javax.swing.JMenu mnuTrogiup;
    private javax.swing.JPanel thanhtrangthai;
    private javax.swing.JToolBar tlbthanhcongcu;
    // End of variables declaration//GEN-END:variables
    private void init() {
        setLocationRelativeTo(null);
        new ChaoJDialog(this, true).setVisible(true);
        new DangNhapJDialog(this, true).setVisible(true);
        Time();
    }

    public void Time() {
        new Timer(10, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date now = new Date();
                SimpleDateFormat format = new SimpleDateFormat("hh:mm:ss a");
                String clock = format.format(now);
                lbgio.setText(clock);
            }
        }).start();
    }

    public void setLayout() {
//   menuitem.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_?, ActionEvent.CTRL_MASK));
    }

}
