/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package duanmau.GiaoDien;

import duanmau.DAO.NguoiHocDAO;
import duanmau.Help.Dialog;
import duanmau.Help.Login;
import duanmau.Help.XDate;
import duanmau.entity.NguoiHoc;
import java.util.Date;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NguyenMinhHau_PS24488
 */
public class Quanlinguoihoc extends javax.swing.JDialog {

    /**
     * Creates new form Quanlichuyende
     */
    NguoiHocDAO dao = new NguoiHocDAO();
    public int row;

    public Quanlinguoihoc(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    void init() {
        setLocationRelativeTo(null);
        this.fillTable();
        this.row = -1;
        this.updateStatus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btggioitinh = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        tab = new javax.swing.JTabbedPane();
        danhsach = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblnguoihoc = new javax.swing.JTable();
        timkiem = new javax.swing.JPanel();
        txttimkiem = new javax.swing.JTextField();
        btntimkiem = new javax.swing.JButton();
        capnhat = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtghichu = new javax.swing.JTextArea();
        txtmanh = new javax.swing.JTextField();
        txthovaten = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        btnthem = new javax.swing.JButton();
        btnleftend = new javax.swing.JButton();
        btnleft = new javax.swing.JButton();
        btnrightend = new javax.swing.JButton();
        btnright = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        btnmoi = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtsdt = new javax.swing.JTextField();
        txtngaysinh = new javax.swing.JTextField();
        rdonam = new javax.swing.JRadioButton();
        rdonu = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản lí người học");
        setIconImage(new ImageIcon(getClass().getResource("/duanmau/image/icon/logo.jpg")).getImage());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Quản lí người học");

        tblnguoihoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã người học", "Họ và tên", "Giới tính", "Ngày sinh", "Số điện thoại", "Email", "Tạo bởi", "Ngày tạo"
            }
        ));
        tblnguoihoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblnguoihocMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tblnguoihoc);
        if (tblnguoihoc.getColumnModel().getColumnCount() > 0) {
            tblnguoihoc.getColumnModel().getColumn(0).setMinWidth(150);
            tblnguoihoc.getColumnModel().getColumn(0).setPreferredWidth(150);
            tblnguoihoc.getColumnModel().getColumn(0).setMaxWidth(200);
            tblnguoihoc.getColumnModel().getColumn(1).setMinWidth(100);
            tblnguoihoc.getColumnModel().getColumn(1).setPreferredWidth(100);
            tblnguoihoc.getColumnModel().getColumn(1).setMaxWidth(200);
            tblnguoihoc.getColumnModel().getColumn(2).setMinWidth(150);
            tblnguoihoc.getColumnModel().getColumn(2).setPreferredWidth(150);
            tblnguoihoc.getColumnModel().getColumn(2).setMaxWidth(200);
        }

        timkiem.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "  Tìm kiếm  ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(153, 153, 255))); // NOI18N

        txttimkiem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txttimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttimkiemActionPerformed(evt);
            }
        });

        btntimkiem.setText("Tìm kiếm");
        btntimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntimkiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout timkiemLayout = new javax.swing.GroupLayout(timkiem);
        timkiem.setLayout(timkiemLayout);
        timkiemLayout.setHorizontalGroup(
            timkiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timkiemLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btntimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        timkiemLayout.setVerticalGroup(
            timkiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timkiemLayout.createSequentialGroup()
                .addGroup(timkiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txttimkiem, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(btntimkiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout danhsachLayout = new javax.swing.GroupLayout(danhsach);
        danhsach.setLayout(danhsachLayout);
        danhsachLayout.setHorizontalGroup(
            danhsachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(danhsachLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(danhsachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(timkiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        danhsachLayout.setVerticalGroup(
            danhsachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, danhsachLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        tab.addTab("Danh sách", danhsach);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Ghi chú");

        txtghichu.setColumns(20);
        txtghichu.setRows(5);
        jScrollPane1.setViewportView(txtghichu);

        btnthem.setText("Thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btnleftend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duanmau/image/icon/leftend.png"))); // NOI18N
        btnleftend.setEnabled(false);
        btnleftend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnleftendActionPerformed(evt);
            }
        });

        btnleft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duanmau/image/icon/left.png"))); // NOI18N
        btnleft.setEnabled(false);
        btnleft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnleftActionPerformed(evt);
            }
        });

        btnrightend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duanmau/image/icon/rightend.png"))); // NOI18N
        btnrightend.setEnabled(false);
        btnrightend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrightendActionPerformed(evt);
            }
        });

        btnright.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duanmau/image/icon/right.png"))); // NOI18N
        btnright.setEnabled(false);
        btnright.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrightActionPerformed(evt);
            }
        });

        btnsua.setText("Sửa");
        btnsua.setEnabled(false);
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        btnmoi.setText("Mới");
        btnmoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmoiActionPerformed(evt);
            }
        });

        btnxoa.setText("Xóa");
        btnxoa.setEnabled(false);
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Mã người học");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setText("Email");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel10.setText("Học và tên");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel11.setText("Giới tính");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel12.setText("Số điện thoại");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel13.setText("Ngày sinh");

        btggioitinh.add(rdonam);
        rdonam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdonam.setText("Nam");
        rdonam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdonamActionPerformed(evt);
            }
        });

        btggioitinh.add(rdonu);
        rdonu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdonu.setText("Nữ");

        javax.swing.GroupLayout capnhatLayout = new javax.swing.GroupLayout(capnhat);
        capnhat.setLayout(capnhatLayout);
        capnhatLayout.setHorizontalGroup(
            capnhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(capnhatLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(capnhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(capnhatLayout.createSequentialGroup()
                        .addComponent(btnthem, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnsua, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnxoa, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnmoi, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(169, 169, 169)
                        .addComponent(btnleftend)
                        .addGap(28, 28, 28)
                        .addComponent(btnleft)
                        .addGap(28, 28, 28)
                        .addComponent(btnright)
                        .addGap(18, 18, 18)
                        .addComponent(btnrightend))
                    .addGroup(capnhatLayout.createSequentialGroup()
                        .addGroup(capnhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(capnhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtmanh, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(txthovaten)
                            .addComponent(txtemail))
                        .addGap(40, 40, 40)
                        .addGroup(capnhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(capnhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(capnhatLayout.createSequentialGroup()
                                .addComponent(rdonam)
                                .addGap(18, 18, 18)
                                .addComponent(rdonu)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtngaysinh)
                            .addComponent(txtsdt)))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );
        capnhatLayout.setVerticalGroup(
            capnhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(capnhatLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(capnhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(capnhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(rdonam)
                        .addComponent(rdonu))
                    .addGroup(capnhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtmanh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(capnhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(capnhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txthovaten, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13)))
                .addGap(40, 40, 40)
                .addGroup(capnhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(41, 41, 41)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(capnhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnthem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnrightend)
                    .addComponent(btnright)
                    .addComponent(btnleft)
                    .addComponent(btnleftend)
                    .addComponent(btnmoi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnxoa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsua, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        btnthem.getAccessibleContext().setAccessibleDescription("25");
        btnsua.getAccessibleContext().setAccessibleDescription("25");
        btnmoi.getAccessibleContext().setAccessibleDescription("25");
        btnxoa.getAccessibleContext().setAccessibleDescription("25");

        tab.addTab("Cập nhật", capnhat);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(tab, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(tab, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        // TODO add your handling code here:
        Update();
    }//GEN-LAST:event_btnsuaActionPerformed

    private void btnleftendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnleftendActionPerformed
        // TODO add your handling code here:
        leftend();
    }//GEN-LAST:event_btnleftendActionPerformed

    private void btnleftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnleftActionPerformed
        // TODO add your handling code here:
        left();
    }//GEN-LAST:event_btnleftActionPerformed

    private void btnrightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrightActionPerformed
        // TODO add your handling code here:
        right();
    }//GEN-LAST:event_btnrightActionPerformed

    private void txttimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttimkiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttimkiemActionPerformed

    private void rdonamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdonamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdonamActionPerformed

    private void btntimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntimkiemActionPerformed
        // TODO add your handling code here:
        timkiem();
    }//GEN-LAST:event_btntimkiemActionPerformed

    private void tblnguoihocMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblnguoihocMouseReleased
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            this.row = tblnguoihoc.getSelectedRow();
//            Dialog.Message(this, String.valueOf(evt.getClickCount()));
            this.edit();
        }
    }//GEN-LAST:event_tblnguoihocMouseReleased

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        // TODO add your handling code here:
        Insert();
    }//GEN-LAST:event_btnthemActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        Delete();
    }//GEN-LAST:event_btnxoaActionPerformed

    private void btnmoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmoiActionPerformed
        // TODO add your handling code here:
        clearForm();
    }//GEN-LAST:event_btnmoiActionPerformed

    private void btnrightendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrightendActionPerformed
        // TODO add your handling code here:
        rightend();
    }//GEN-LAST:event_btnrightendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhapJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhapJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhapJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhapJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Quanlinguoihoc dialog = new Quanlinguoihoc(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btggioitinh;
    private javax.swing.JButton btnleft;
    private javax.swing.JButton btnleftend;
    private javax.swing.JButton btnmoi;
    private javax.swing.JButton btnright;
    private javax.swing.JButton btnrightend;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btntimkiem;
    private javax.swing.JButton btnxoa;
    private javax.swing.JPanel capnhat;
    private javax.swing.JPanel danhsach;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rdonam;
    private javax.swing.JRadioButton rdonu;
    private javax.swing.JTabbedPane tab;
    private javax.swing.JTable tblnguoihoc;
    private javax.swing.JPanel timkiem;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextArea txtghichu;
    private javax.swing.JTextField txthovaten;
    private javax.swing.JTextField txtmanh;
    private javax.swing.JTextField txtngaysinh;
    private javax.swing.JTextField txtsdt;
    private javax.swing.JTextField txttimkiem;
    // End of variables declaration//GEN-END:variables

    void fillTable() {
        DefaultTableModel model = (DefaultTableModel) tblnguoihoc.getModel();
        model.setRowCount(0);
        try {
            String tk = txttimkiem.getText().trim();
            List<NguoiHoc> lst = null;
            if (!tk.equals("")) {
                lst = dao.SelectByKeyword(tk);
            } else {
                lst = dao.SelectAll();
            }
            for (NguoiHoc entity : lst) {
                Object[] row = {entity.getMaNH(), entity.getHoten(), entity.isGioiTinh() == true ? "Nam" : "Nữ", XDate.toString(entity.getNgaySinh(), "dd-MM-yyyy"), entity.getDienThoai(), entity.getEmail(), entity.getMaNV(), XDate.toString(entity.getNgayDK(), "dd-MM-yyyy")};
                model.addRow(row);
            }
            tblnguoihoc.setDefaultEditor(Object.class, null);
        } catch (Exception e) {
            Dialog.Message(this, "Không thể truy vấn dữ liệu !");
        }
    }

    void setForm(NguoiHoc entity) {
        txthovaten.setText(entity.getHoten());
        txtemail.setText(entity.getEmail());
        txtmanh.setText(entity.getMaNH());
        txtngaysinh.setText(XDate.toString(entity.getNgaySinh(), "dd/MM/yyyy"));
        txtghichu.setText(entity.getGhiChu());
        txtsdt.setText(entity.getDienThoai());
        rdonam.setSelected(entity.isGioiTinh());
        rdonu.setSelected(!entity.isGioiTinh());
    }

    void clearForm() {
//        NguoiHoc entity = new NguoiHoc(0);
//        this.setForm(entity);
        txthovaten.setText("");
        txtemail.setText("");
        txtmanh.setText("");
        txtngaysinh.setText("");
        txtghichu.setText("");
        txtsdt.setText("");
        rdonam.setSelected(true);
        this.row = -1;
        this.updateStatus();
    }

    void edit() {
        String manh = (String) tblnguoihoc.getValueAt(this.row, 0);
        NguoiHoc entity = dao.SelectID(manh);
        this.setForm(entity);
        tab.setSelectedIndex(1);
        this.updateStatus();
    }

    NguoiHoc getForm() {
        NguoiHoc entity = new NguoiHoc();
        entity.setMaNH(txtmanh.getText());
        entity.setHoten(txthovaten.getText());
        entity.setDienThoai(txtsdt.getText());
        entity.setEmail(txtemail.getText());
        entity.setNgaySinh(XDate.toDate(txtngaysinh.getText(), "dd-MM-yyyy"));
        entity.setNgayDK(new Date());
        entity.setMaNV(Login.user.getMaNV());
        entity.setGioiTinh(rdonam.isSelected());
        entity.setGhiChu(txtghichu.getText());
        return entity;
    }

    void Insert() {
        if (checkValidate()) {
            NguoiHoc entity = getForm();
//         Dialog.Message(this,String.valueOf(cd.getMaCD())+" - "+String.valueOf(cd.getTenCD())+" - "+String.valueOf(cd.getHocPhi())+" - "+String.valueOf(cd.getThoiLuong())+" - "+String.valueOf(cd.getHinh())+" - "+String.valueOf(cd.getMoTa()));
            try {
                dao.Insert(entity);
                this.fillTable();
                this.clearForm();
                Dialog.Message(this, "Thêm mới thành công");
            } catch (Exception e) {
                Dialog.Message(this, "Đã tồn tại mã chuyên đề tương tự, không thể thêm mới");
            }
        }
    }

    void Update() {
        if (checkValidate()) {
            NguoiHoc entity = getForm();
            try {
                dao.Update(entity);
                this.fillTable();
                Dialog.Message(this, "Cập nhật thành công");

            } catch (Exception e) {
                Dialog.Message(this, "Cập nhật thất bại");
            }
        }
    }

    void Delete() {
        String macd = txtmanh.getText();
        if (Dialog.Confirm(this, "Bạn thật sự muốn xóa người học này ?")) {
            try {
                dao.Remove(macd);
                this.fillTable();
                this.clearForm();
                Dialog.Message(this, "Xóa thành công");
            } catch (Exception e) {
                Dialog.Message(this, "Xảy ra lỗi, xóa thất bại");
            }
        }
    }

    void rightend() {
        this.row = 0;
        this.edit();
    }

    void leftend() {
        this.row = tblnguoihoc.getRowCount() - 1;
        this.edit();
    }

    void right() {
        if (this.row < tblnguoihoc.getRowCount() - 1) {
            this.row++;
            this.edit();
        }
    }

    void left() {
        if (this.row > 0) {
            this.row--;
            this.edit();
        }
    }

    void updateStatus() {
        boolean edit = (this.row >= 0);
        boolean leftend = (this.row == 0);
        boolean rightend = (this.row == tblnguoihoc.getRowCount() - 1);
        //trang thai from
        txtmanh.setEditable(!edit);
        btnthem.setEnabled(!edit);
        btnsua.setEnabled(edit);
        btnxoa.setEnabled(edit);
        //nut chuyen tiep
        btnleft.setEnabled(edit && !leftend);
        btnleftend.setEnabled(edit && !leftend);
        btnright.setEnabled(edit && !rightend);
        btnrightend.setEnabled(edit && !rightend);
    }

    void timkiem() {
        this.fillTable();
        this.row = -1;
        this.clearForm();
        this.updateStatus();
    }

    boolean checkValidate() {
        if (txtmanh.getText().equals("")) {
            txtmanh.requestFocus();
            Dialog.Message(this, "Vui lòng nhập đầy đủ thông tin");
            return false;
        } else if (txthovaten.getText().equals("")) {
            txthovaten.requestFocus();
            Dialog.Message(this, "Vui lòng nhập đầy đủ thông tin");
            return false;
        } else if (txtngaysinh.getText().equals("")) {
            txtngaysinh.requestFocus();
            Dialog.Message(this, "Vui lòng nhập đầy đủ thông tin");
            return false;
        } else if (txtemail.getText().equals("")) {
            txtemail.requestFocus();
            Dialog.Message(this, "Vui lòng nhập đầy đủ thông tin");
            return false;
        } else if (txtsdt.getText().equals("")) {
            txtsdt.requestFocus();
            Dialog.Message(this, "Vui lòng nhập đầy đủ thông tin");
            return false;
        }
        String chkemail = "\\w+@\\w{3,8}+\\.+\\w{2,4}";
        String chksdt = "[0-9]{9,11}";
        try{
            Date d = XDate.toDate(txtngaysinh.getText(), "dd-MM-yyyy");
        }catch(Exception e){
            Dialog.Message(this, "Vui lòng nhập đúng định dạng dd-mm-yyyy");
        }
        if (!txtemail.getText().matches(chkemail)) {
            Dialog.Message(this, "Vui lòng nhập đúng định dạng email");
            txtemail.requestFocus();
            return false;
        } else if (!txtsdt.getText().matches(chksdt)) {
            Dialog.Message(this, "Vui lòng nhập đúng định dạng số điện thoại");
            txtsdt.requestFocus();
            return false;
        }
        return true;
    }
}
